# -*- coding: utf-8 -*-
"""
أكواد الأخطاء القياسية الموحدة للمنظومة (Standardized Internal Error Codes):
- ثوابت محددة ومستقرة للأخطاء التشغيلية والأمنية.
- تمنع كشف أسماء الاستثناءات الداخلية في Python للمستخدمين.
"""


class ErrorCode:
    # المصادقة والصلاحيات واسترداد الحسابات (Authentication & Account Recovery)
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
    FORBIDDEN_ORIGIN = "FORBIDDEN_ORIGIN"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED"
    AUTH_LOCKED_OUT = "AUTH_LOCKED_OUT"
    PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK"
    CSRF_FAILED = "CSRF_FAILED"
    FIRST_ADMIN_ALREADY_EXISTS = "FIRST_ADMIN_ALREADY_EXISTS"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    RECOVERY_INVALID_CREDENTIAL = "RECOVERY_INVALID_CREDENTIAL"
    RECOVERY_PIN_REQUIRED = "RECOVERY_PIN_REQUIRED"
    RECOVERY_LOCKED_OUT = "RECOVERY_LOCKED_OUT"
    RECOVERY_TOKEN_EXPIRED = "RECOVERY_TOKEN_EXPIRED"
    RECOVERY_NOT_CONFIGURED = "RECOVERY_NOT_CONFIGURED"

    # التحقق والمدخلات (Validation & Requests)
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    RATE_LIMITED = "RATE_LIMITED"

    # معالجة واستخراج وتدقيق الملفات (File Processing, Upload & Extraction)
    FILE_EXTRACTION_FAILED = "FILE_EXTRACTION_FAILED"
    FILE_UNSUPPORTED = "FILE_UNSUPPORTED"
    FILE_UNSUPPORTED_TYPE = "FILE_UNSUPPORTED_TYPE"
    FILE_CORRUPTED = "FILE_CORRUPTED"
    FILE_EMPTY = "FILE_EMPTY"
    FILE_ENCRYPTED = "FILE_ENCRYPTED"
    FILE_UNREADABLE = "FILE_UNREADABLE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_SIGNATURE_MISMATCH = "FILE_SIGNATURE_MISMATCH"
    FILE_MALICIOUS = "FILE_MALICIOUS"

    # تدقيق حزم DOCX و PDF وحدود الموارد (Archive & Resource Limits)
    DOCX_ARCHIVE_UNSAFE = "DOCX_ARCHIVE_UNSAFE"
    DOCX_RESOURCE_LIMIT = "DOCX_RESOURCE_LIMIT"
    PDF_PAGE_LIMIT = "PDF_PAGE_LIMIT"
    BATCH_LIMIT_EXCEEDED = "BATCH_LIMIT_EXCEEDED"

    # التعرف الضوئي والمطابقة الدلالية (OCR & Semantic)
    OCR_FAILED = "OCR_FAILED"
    OCR_UNAVAILABLE = "OCR_UNAVAILABLE"
    SEMANTIC_FAILED = "SEMANTIC_FAILED"
    SEMANTIC_UNAVAILABLE = "SEMANTIC_UNAVAILABLE"

    # محرك ومهام الفحص (Scan Jobs & Workflows)
    SCAN_FAILED = "SCAN_FAILED"
    SCAN_INTERRUPTED = "SCAN_INTERRUPTED"
    WORKFLOW_INVALID_TRANSITION = "WORKFLOW_INVALID_TRANSITION"

    # قاعدة البيانات والتخزين (Database & Storage)
    DATABASE_ERROR = "DATABASE_ERROR"
    DATABASE_LOCKED = "DATABASE_LOCKED"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    STORAGE_ERROR = "STORAGE_ERROR"
    STORAGE_FULL = "STORAGE_FULL"

    # النسخ الاحتياطي والاستعادة والنزاهة (Backup, Restore & Integrity)
    BACKUP_FAILED = "BACKUP_FAILED"
    RESTORE_FAILED = "RESTORE_FAILED"
    FILE_INTEGRITY_FAILED = "FILE_INTEGRITY_FAILED"

    # نزاهة التقارير والاعتماد والمراجعات (Report Integrity, Finalization & Lineage)
    REPORT_NOT_READY = "REPORT_NOT_READY"
    REPORT_ALREADY_FINALIZED = "REPORT_ALREADY_FINALIZED"
    REPORT_FINALIZATION_FAILED = "REPORT_FINALIZATION_FAILED"
    REPORT_INTEGRITY_FAILED = "REPORT_INTEGRITY_FAILED"
    REPORT_LEGACY_UNVERIFIABLE = "REPORT_LEGACY_UNVERIFIABLE"
    REPORT_REVISION_CONFLICT = "REPORT_REVISION_CONFLICT"
    REPORT_INPUT_INTEGRITY_FAILED = "REPORT_INPUT_INTEGRITY_FAILED"
    REPORT_VOIDED = "REPORT_VOIDED"

    # حوكمة وتتبع وإصدارات قاعدة المراجع (Reference Corpus Governance & Index State)
    REFERENCE_DUPLICATE = "REFERENCE_DUPLICATE"
    REFERENCE_NOT_FOUND = "REFERENCE_NOT_FOUND"
    REFERENCE_INTEGRITY_FAILED = "REFERENCE_INTEGRITY_FAILED"
    REFERENCE_ALREADY_RETIRED = "REFERENCE_ALREADY_RETIRED"
    REFERENCE_SUPERSESSION_CONFLICT = "REFERENCE_SUPERSESSION_CONFLICT"
    CORPUS_VERSION_CONFLICT = "CORPUS_VERSION_CONFLICT"
    CORPUS_INDEX_STALE = "CORPUS_INDEX_STALE"
    CORPUS_INDEX_BUILD_FAILED = "CORPUS_INDEX_BUILD_FAILED"

    # إدارة طابور المهام والتنفيذ (Phase 17: Job Management & Queue Discipline)
    JOB_QUEUE_FULL = "JOB_QUEUE_FULL"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_ALREADY_RUNNING = "JOB_ALREADY_RUNNING"
    JOB_ALREADY_COMPLETED = "JOB_ALREADY_COMPLETED"
    JOB_CANCEL_NOT_ALLOWED = "JOB_CANCEL_NOT_ALLOWED"
    JOB_CANCELLED = "JOB_CANCELLED"
    JOB_INTERRUPTED = "JOB_INTERRUPTED"
    JOB_RETRY_LIMIT_REACHED = "JOB_RETRY_LIMIT_REACHED"
    JOB_CLAIM_CONFLICT = "JOB_CLAIM_CONFLICT"
    JOB_STUCK = "JOB_STUCK"
    WORKER_UNAVAILABLE = "WORKER_UNAVAILABLE"

    # أخطاء الخادم العامة (General System Errors)
    INTERNAL_ERROR = "INTERNAL_ERROR"
    ANTIVIRUS_UNAVAILABLE = "ANTIVIRUS_UNAVAILABLE"
    ANTIVIRUS_SCAN_FAILED = "ANTIVIRUS_SCAN_FAILED"
